// libs
import Head from "next/head";

// components/modules
import CenterComponent from '~/modules/layout/center.component';
import HeaderComponent from '~/modules/layout/header.component';
import PostsView from '~/modules/post/posts-view.component';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CenterComponent>
        <>
          <HeaderComponent />
          <h1 className="text-5xl font-extrabold tracking-tigh sm:text-[5rem]">
            Twitter Clone
          </h1>
          <h2>Posts</h2>
          <PostsView />
        </>
      </CenterComponent>
    </>
  );
};
